// const min = require("min").min;
// const summ = require("summ").summ;
// const abs = require("abs").abs;
const { customMath } = require("math");
console.log("\nMin");
console.log("======================\n");
customMath.min([45, 45, 45, 23]);
console.log("\nSumm");
console.log("======================\n");
customMath.summ(10, 25, 35);
console.log("\nAbs");
console.log("======================\n");
customMath.abs(-213);
