const min = require("min").min;
const summ = require("summ").summ;
const abs = require("abs").abs;
console.log("\nMin");
console.log("======================\n");
min([45, 45, 45, 23]);
console.log("\nSumm");
console.log("======================\n");
summ(10, 25, 35);
console.log("\nAbs");
console.log("======================\n");
abs(-213);
